/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RunMigrationsRouteImport } from './routes/run-migrations'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatStreamRouteImport } from './routes/api/chat-stream'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedMetricsRouteImport } from './routes/_authenticated/metrics'
import { Route as AuthenticatedFollowUpsRouteImport } from './routes/_authenticated/follow-ups'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAboutRouteImport } from './routes/_authenticated/about'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated/clients.index'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated/clients.new'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'

const RunMigrationsRoute = RunMigrationsRouteImport.update({
  id: '/run-migrations',
  path: '/run-migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/api/chat-stream',
  path: '/api/chat-stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetricsRoute = AuthenticatedMetricsRouteImport.update({
  id: '/metrics',
  path: '/metrics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFollowUpsRoute = AuthenticatedFollowUpsRouteImport.update({
  id: '/follow-ups',
  path: '/follow-ups',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAboutRoute = AuthenticatedAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/run-migrations': typeof RunMigrationsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/run-migrations': typeof RunMigrationsRoute
  '/about': typeof AuthenticatedAboutRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/metrics': typeof AuthenticatedMetricsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/run-migrations': typeof RunMigrationsRoute
  '/_authenticated/about': typeof AuthenticatedAboutRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/follow-ups': typeof AuthenticatedFollowUpsRoute
  '/_authenticated/metrics': typeof AuthenticatedMetricsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/api/chat-stream': typeof ApiChatStreamRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/run-migrations'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/follow-ups'
    | '/metrics'
    | '/profile'
    | '/api/chat-stream'
    | '/clients/$id'
    | '/clients/new'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/run-migrations'
    | '/about'
    | '/admin'
    | '/analytics'
    | '/follow-ups'
    | '/metrics'
    | '/profile'
    | '/api/chat-stream'
    | '/clients/$id'
    | '/clients/new'
    | '/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/run-migrations'
    | '/_authenticated/about'
    | '/_authenticated/admin'
    | '/_authenticated/analytics'
    | '/_authenticated/follow-ups'
    | '/_authenticated/metrics'
    | '/_authenticated/profile'
    | '/api/chat-stream'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  RunMigrationsRoute: typeof RunMigrationsRoute
  ApiChatStreamRoute: typeof ApiChatStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/run-migrations': {
      id: '/run-migrations'
      path: '/run-migrations'
      fullPath: '/run-migrations'
      preLoaderRoute: typeof RunMigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat-stream': {
      id: '/api/chat-stream'
      path: '/api/chat-stream'
      fullPath: '/api/chat-stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metrics': {
      id: '/_authenticated/metrics'
      path: '/metrics'
      fullPath: '/metrics'
      preLoaderRoute: typeof AuthenticatedMetricsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/follow-ups': {
      id: '/_authenticated/follow-ups'
      path: '/follow-ups'
      fullPath: '/follow-ups'
      preLoaderRoute: typeof AuthenticatedFollowUpsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/about': {
      id: '/_authenticated/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AuthenticatedAboutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAboutRoute: typeof AuthenticatedAboutRoute
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedFollowUpsRoute: typeof AuthenticatedFollowUpsRoute
  AuthenticatedMetricsRoute: typeof AuthenticatedMetricsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAboutRoute: AuthenticatedAboutRoute,
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedFollowUpsRoute: AuthenticatedFollowUpsRoute,
  AuthenticatedMetricsRoute: AuthenticatedMetricsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  RunMigrationsRoute: RunMigrationsRoute,
  ApiChatStreamRoute: ApiChatStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
