// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let _supabase: ReturnType<typeof createClient<Database>> | undefined;
let _initPromise: Promise<ReturnType<typeof createClient<Database>>> | undefined;

async function createSupabaseClientAsync(): Promise<ReturnType<typeof createClient<Database>>> {
  let url: string | undefined = (import.meta as any).env?.VITE_SUPABASE_URL;
  let key: string | undefined = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY;

  // If not baked, fetch from middleware at runtime (so .env only needs VITE_API_URL)
  if (!url || !key) {
    const apiUrl =
      (import.meta as any).env?.VITE_API_URL ||
      (process.env as any).VITE_API_URL ||
      (process.env as any).API_URL;
    if (apiUrl) {
      try {
        const res = await fetch(`${apiUrl.replace(/\/$/, "")}/api/config`);
        if (res.ok) {
          const json = await res.json();
          url = url || json.url;
          key = key || json.anonKey;
        }
      } catch (e) {
        console.warn("[Supabase] Failed to fetch config from middleware:", e);
      }
    }
  }

  url = url || (process.env as any).SUPABASE_URL || (process.env as any).VITE_SUPABASE_URL;
  key = key || (process.env as any).SUPABASE_PUBLISHABLE_KEY || (process.env as any).VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!url || !key) {
    throw new Error("Supabase not configured");
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export async function initSupabase(): Promise<ReturnType<typeof createClient<Database>>> {
  if (_supabase) return _supabase;
  if (_initPromise) return _initPromise;
  _initPromise = createSupabaseClientAsync().then((c) => {
    _supabase = c;
    return c;
  });
  return _initPromise;
}

function getSupabase(): ReturnType<typeof createClient<Database>> {
  if (!_supabase) {
    throw new Error("Supabase not initialized. Call initSupabase() in root loader first.");
  }
  return _supabase;
}

// Proxy that ensures init before any property access (for backwards compat)
export const supabase = new Proxy({} as ReturnType<typeof createClient<Database>>, {
  get(_target, prop: string | symbol, _receiver) {
    const client = getSupabase();
    return Reflect.get(client as any, prop);
  },
});
