// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

let _supabase: ReturnType<typeof createClient<Database>> | undefined;
let _initPromise: Promise<ReturnType<typeof createClient<Database>>> | undefined;

async function createSupabaseClientAsync(): Promise<ReturnType<typeof createClient<Database>>> {
  let url: string | undefined = (import.meta as any).env?.VITE_SUPABASE_URL;
  let key: string | undefined = (import.meta as any).env?.VITE_SUPABASE_PUBLISHABLE_KEY;

  // If not baked, fetch from middleware at runtime (so .env only needs VITE_API_URL)
  // Retry for cold-start (Fly/Railway may take ~15s+ to wake)
  if (!url || !key) {
    const apiUrl =
      (import.meta as any).env?.VITE_API_URL ||
      (process.env as any).VITE_API_URL ||
      (process.env as any).API_URL;
    // When deployed on Fly, VITE_API_URL may not be baked — fallback to same-origin
    // so the fetch still works without extra env wiring.
    const configUrl = apiUrl ? `${apiUrl.replace(/\/$/, "")}/api/config` : "/api/config";
    const maxAttempts = 6;
    for (let attempt = 0; attempt < maxAttempts; attempt++) {
      try {
        const ctrl = new AbortController();
        const timeoutMs = attempt < 2 ? 10000 : 15000;
        const t = setTimeout(() => ctrl.abort(), timeoutMs);
        const res = await fetch(configUrl, { signal: ctrl.signal });
        clearTimeout(t);
        if (res.ok) {
          const json = await res.json();
          url = url || json.url;
          key = key || json.anonKey;
          break;
        }
        // Non-OK response — retry with backoff (server may be waking)
        if (attempt < maxAttempts - 1) {
          const delay = Math.min(1000 * Math.pow(1.5, attempt), 8000);
          await new Promise((r) => setTimeout(r, delay));
        } else {
          console.warn("[Supabase] /api/config returned non-OK:", res.status);
        }
      } catch (e) {
        if (attempt === maxAttempts - 1) {
          console.warn("[Supabase] Failed to fetch config after retries:", e);
        } else {
          const delay = Math.min(1000 * Math.pow(1.5, attempt), 8000);
          await new Promise((r) => setTimeout(r, delay));
        }
      }
    }
  }

  url = url || (process.env as any).SUPABASE_URL || (process.env as any).VITE_SUPABASE_URL;
  key = key || (process.env as any).SUPABASE_PUBLISHABLE_KEY || (process.env as any).VITE_SUPABASE_PUBLISHABLE_KEY;

  if (!url || !key) {
    throw new Error("Supabase not configured");
  }

  return createClient<Database>(url, key, {
    auth: {
      storage: typeof window !== "undefined" ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
}

export async function initSupabase(): Promise<ReturnType<typeof createClient<Database>>> {
  if (_supabase) return _supabase;
  if (_initPromise) return _initPromise;
  _initPromise = createSupabaseClientAsync()
    .then((c) => {
      _supabase = c;
      return c;
    })
    .catch((e) => {
      _initPromise = undefined;
      throw e;
    });
  return _initPromise;
}

function getSupabase(): ReturnType<typeof createClient<Database>> {
  if (_supabase) return _supabase;
  // Start init if not already in progress, then suspend (React Suspense)
  // until the promise settles — shows pending/loading instead of crashing.
  if (!_initPromise) _initPromise = initSupabase().catch(() => undefined) as any;
  throw _initPromise;
}

// Proxy that suspends until init completes, then delegates to the real client.
export const supabase: ReturnType<typeof createClient<Database>> = new Proxy(
  {} as ReturnType<typeof createClient<Database>>,
  {
    get(_target, prop: string | symbol, _receiver) {
      const client = getSupabase();
      const val = Reflect.get(client as any, prop);
      // Bind methods so `this` stays correct when accessed via proxy.
      if (typeof val === "function") return val.bind(client);
      return val;
    },
  },
) as any;
